FROM alpine:latest

RUN apk update
RUN apk add --update --no-cache php7
RUN addgroup tal
RUN adduser -h /home/tal -g '' -s /bin/ash -G tal -D tal
RUN chown nobody:nogroup /mnt

WORKDIR /mnt

# compile
COPY --chown=tal:tal launch.sh /home/tal/launch.sh
COPY --chown=root:root php.ini /etc/php7/php.ini

# leave root user
USER tal:tal
# set default entry point
ENTRYPOINT /bin/sh /home/tal/launch.sh
