FROM alpine:latest

RUN apk update
RUN apk add --update mono  --repository https://dl-3.alpinelinux.org/alpine/edge/testing/
RUN addgroup tal
RUN adduser -h /home/tal -g '' -s /bin/ash -G tal -D tal
RUN chown tal:tal /mnt

WORKDIR /mnt

# compile
COPY --chown=tal:tal launch.sh /home/tal/launch.sh
# leave root user
USER tal:tal
RUN mkdir /mnt/in
RUN mkdir /mnt/out

# set default entry point
#ENTRYPOINT /bin/sh /home/tal/launch.sh




