name: Docker Image CI
on:
  schedule:
    - cron: '0 4 * * *'
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Ada Docker image
      working-directory: ./docker/ada
      run: docker build . --file Dockerfile --tag tal-ada:latest && docker tag tal-ada:latest fderepas/tal-ada:latest && docker push fderepas/tal-ada:latest
