name: cpp

on:
  # Trigger the workflow every night at 4:9 AM UTC
  schedule:
    - cron: '9 4 * * *'

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-tests-on-local-machine:
    runs-on: self-hosted

    steps:
      # Check out repository's code onto local machine
      - name: Check out code
        uses: actions/checkout@v4

      # Testing command
      - name: Build images
        run: |
          echo "Building images cpp"
          bash .github/workflows/rebuild_cpp.sh
